### ISSUE TITLE
Add Variability to Spawned Hallways

### ISSUE THREAD

**Issue by CheerfulSatchel** [theAmbientOrange/star-runner-2019#4]
Currently the type-casting in the actor spawn functionality restricts our ability to only spawn x3 hallways.

We must fix this.

**Comment by Lancewiu** [comment]
I think we have a solution with the cpp branch right?

**Comment by theAmbientOrange** [comment]
@Lancewiu Indeed we do~~ I will add this to the PR as well 😂
