### ISSUE TITLE
Game Over on Wall Collision

### ISSUE THREAD

**Issue by CheerfulSatchel** [theAmbientOrange/star-runner-2019#6]
The game is over when the player fails to turn in time and instead runs into a wall.
- [ ] Death sound plays
- [ ] Camera turns straight up
- [ ] HUD should appear on death (Depends on #11 )

**Comment by Lancewiu** [comment]
Immediate restart for now or is the goal to have a HUD thing?

**Comment by CheerfulSatchel** [comment]
HUD thing 😸
