### ISSUE TITLE
Upgrade to Unreal Engine 4.22.2

### ISSUE THREAD

**Issue by CheerfulSatchel** [theAmbientOrange/star-runner-2019#7]
Upgrade the engine and its libraries from `4.22.1` to `4.22.2`.

**Comment by Lancewiu** [comment]
So I've tested this for b538bc8 and it seems that no changes are necessary.  The point release doesn't break anything from what I've seen.  Do you want to confirm as well?

**Comment by CheerfulSatchel** [comment]
Sure, I will confirm it and then probably merge it 😃

**Comment by Lancewiu** [comment]
Nothing needed to be changed so I'm closing this.
